name: Food for Fun
favicon: null
layout_spectrum: 0.99492
typography_spectrum: 0.7479183354880661
title: Food for Fun
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.872352609410882
  lightness: 0.58557722507976
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
